services:
  smartmart-psql-service:
    image: postgres:17
    container_name: smartmart-psql
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=smartmart
      - POSTGRES_PASSWORD=smartmart
      - POSTGRES_DB=smartmart
    # volumes:
    #   - postgres_data:/var/lib/postgresql/data
